### ISSUE TITLE
No MCC config file in the project ?

### ISSUE THREAD

**Issue by SkippyFrance** [microchip-pic-avr-solutions/pic-lightblue-explorer-demo#1]
Hello, I don't see the MCC (*.mc3) config file in the project. How I can update this project to add a click board not remaking the complete config in MCC ?

**Comment by mazuigor** [comment]
same question

**Comment by WillChuang23158** [comment]
Same question, thanks.

**Comment by gpgithubtest123** [comment]
should be marked as closed. the .mc3 file has been added on the new release.
