### ISSUE TITLE
Is there any way to use a custom GATT Protocol with the PIC-BLE Development board?

### ISSUE THREAD

**Issue by VladislavSmolyanoy** [microchip-pic-avr-solutions/pic-lightblue-explorer-demo#2]

**Comment by VladislavSmolyanoy** [comment]
Is it possible to create custom Services and Characteristics?

**Comment by gpgithubtest123** [comment]
Yes, it is possible with the RN4870. and thus, the PIC BLE board.
I think the better venue is asking this in the forums or Microchip Technical Support.
